name: admin_panel_for_library
description: "admin_panel_for_library"

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Купертиновские иконки
  cupertino_icons: ^1.0.2
  #Взаимодействие с REST
  dio: ^5.4.3+1
  #Стейт менеджер
  flutter_bloc: ^8.1.5
  #Доступ к файловой дирректории
  file_picker: ^8.0.0+1
  #Кодогенерация
  build_runner: ^2.4.9
  #Генерация моделей
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  #Сериализация
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  #драгиндроп файла
  flutter_dropzone: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700